# ./.github/workflows/openselery
# Use Openselery as a simple Github action on your project workflow.
# For configuration create an .openselery.yml file in your project repo.
name: openselery

on:
  push:
    branches: 
      - master        
env: 
    RESULTSDIR: /home/runner/work/.openselery/results/
jobs:
  openselery:
    name: openselery
    runs-on: ubuntu-latest
    steps:
      # Check out the repo openselery is working on.
      - uses: actions/checkout@v1
      - uses: protontypes/actionselery@v0.0.2
      -  env: 
          GITHUB_TOKEN_CI: ${{ secrets.GITHUB_TOKEN }}
          LIBRARIES_API_KEY_CI: ${{ secrets.LIBRARIES_API_KEY }}
          COINBASE_TOKEN_CI: ${{ secrets.COINBASE_TOKEN }}
          COINBASE_SECRET_CI: ${{ secrets.COINBASE_SECRET }}
