name: seleryaction
        
on:
  push:
    branches: 
      - master  

jobs:
  openselery:
    name: seleryaction
    runs-on: ubuntu-latest
    steps:
      # Check out the repo openselery is working on.
      - uses: actions/checkout@v1 
      - name: print Repository_name and folder
        run: |
              REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")
              echo ${HOME}/work/${REPOSITORY_NAME}/${REPOSITORY_NAME}
              ls ${HOME}/work/${REPOSITORY_NAME}/${REPOSITORY_NAME}
              echo "::set-env name=TARGET_PROJECT::${HOME}/work/${REPOSITORY_NAME}/${REPOSITORY_NAME}"
              echo "::set-env name=GITHUB_REPOSITORY_NEW::$GITHUB_REPOSITORY"

        
      - name: Pull openselery from dockerhub
        run: docker pull protontypes/openselery

      #- name: Build openselery from repo dockerfile
      #  run: docker build -t openselery .

      - name: Set env variables for all following jobs
        run:  |
              echo "::set-env name=results_folder::${HOME}/results_folder"
              echo "::set-env name=config_folder::${HOME}/config_folder"
              
      - name: Create result and config folder
        run:  |
               mkdir -vp $results_folder
               mkdir -vp $config_folder
      - name: Give everyone permission to write to this folder
        run: chmod a+rw $results_folder $config_folder
      - name: Create openselery configuation
        run: |
              echo "Use existing local selery.yml from directory: ${TARGET_PROJECT}"
              cat ${TARGET_PROJECT}/selery.yml
              cp ${TARGET_PROJECT}/selery.yml $config_folder/selery.yml
      - name: Add additional tooling list
        run: |
              echo "Use existing local selery.yml"
              cat ${TARGET_PROJECT}/tooling_repos.yml
              cp ${TARGET_PROJECT}/tooling_repos.yml $config_folder/tooling_repos.yml  

      - name: Run openselery on sources
        run:  > 
                docker run --rm 
                --env GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} 
                --env LIBRARIES_API_KEY=${{ secrets.LIBRARIES_API_KEY }}
                --env COINBASE_TOKEN=${{ secrets.COINBASE_TOKEN }}
                --env COINBASE_SECRET=${{ secrets.COINBASE_SECRET }}
                -v $PWD/:/home/selery/runningrepo/ 
                -v $results_folder:/home/selery/results/
                -v $config_folder:/home/selery/config/ 
                protontypes/openselery 
                --directory=/home/selery/runningrepo/ --config=/home/selery/config/selery.yml  --results_dir=/home/selery/results/  --tooling=/home/selery/config/tooling_repos.yml
        # Upload the receipt file to github artifact.
      - uses: actions/upload-artifact@v1
        with:
          name: selery_dump
          path: /home/runner/results_folder

      - name: Check for payout receipt.txt
        run: | 
              cat ${results_folder}/receipt.txt 
              echo "Payout receipt found"
 
      - name: Checkout Wiki Repo
        uses: actions/checkout@v2
        with:
            repository: ${{ env.GITHUB_REPOSITORY_NEW }}.wiki
            path: wiki
            
      - name: Copy balance badge json files and visualization files to wiki
        run: |
         echo "Change dir to ${HOME}/work"
         cd ./wiki
         mkdir -p openselery       
         cp ${results_folder}/balance_badge.json ./openselery/
         cp ${results_folder}/native_balance_badge.json ./openselery/
         cp ${results_folder}/transactions_per_day.png ./openselery/
         cp ${results_folder}/transactions_per_month.png ./openselery/
         cp ${results_folder}/transactions_per_user.png ./openselery/
         cp ${results_folder}/wallet_balance_per_day.png ./openselery/
         cp ${results_folder}/wallet_qrcode.png ./openselery/
         git config user.name github-actions
         git config user.email github-actions@github.com
         git status
         git add . -A
         git commit -m "Action generated"
                
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.PAT_SELERY }}
         repository: ${{ env.GITHUB_REPOSITORY_NEW }}.wiki
         directory: wiki        
        

